site_name: nanopub
site_description: Python client for Nanopublications
site_author: Robin Richardson, Sven van der Burg, Vincent Emonet
site_url: https://fair-workflows.github.io/nanopub
repo_name: fair-workflows/nanopub
repo_url: https://github.com/fair-workflows/nanopub
edit_uri: "edit/main/docs/"
copyright: Copyright &copy; 2020 Robin Richardson, Sven van der Burg
# docs_dir: "."

theme:
  name: "material"
  favicon: assets/icon.png
  logo: assets/icon.png
  # icon:
  #   logo: material/microscope
  language: en
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow


nav:
  - Getting started:
    - Getting started: index.md
    - What are Nanopublications?: getting-started/what-are-nanopubs.md
    - Setup instructions: getting-started/setup.md
    - The nanopub test server: getting-started/test-server.md
    - Development: getting-started/development.md

  - Publishing:
    - Publish nanopublications: publishing/publish-nanopublications.md
    - Using the nanopublication's namespace: publishing/using-publication-namespace.md
    - Setting publication info and provenance: publishing/setting-subgraphs.md
    - Retracting a nanopublication: publishing/retraction.md
    - Publish with the commandline: publishing/publish-with-cli.md
    # - Legacy Publication object: publishing/publishing-nanopublications.md

  - Searching:
    - Searching: searching/searching.md
    - Fetching: searching/fetching.md

  - API Reference:
    - Client: reference/client.md
    - Nanopub: reference/nanopub.md
    - Config: reference/config.md
    - Profile: reference/profile.md
    - Namespaces: reference/namespaces.md

  - "<span>Issues&nbsp;&nbsp;<i class='fa-solid fa-arrow-up-right-from-square'></i></span>": https://github.com/fair-workflows/nanopub/issues" target="_blank
# https://fontawesome.com/icons/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/


plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    # custom_templates: templates
    watch:
      - nanopub

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - smarty


extra_css:
  - assets/custom.css

extra_javascript:
  - assets/fontawesome.min.js
  - assets/solid.min.js


extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nanopub
    - icon: fontawesome/brands/github
      link: https://github.com/fair-workflows
    # - icon: fontawesome/brands/docker
    #   link: https://github.com/orgs/fair-workflows/packages
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/
