from rdflib import Dataset

from nanopub import Nanopub
from nanopub.utils import MalformedNanopubError
from nanopub_testsuite_connector import NanopubTestSuite, TestSuiteSubfolder
from tests.conftest import java_wrap, testsuite_conf
import pytest


def test_testsuite_valid_plain(testsuite: NanopubTestSuite):
    for entry in testsuite.get_valid(TestSuiteSubfolder.PLAIN):
        print(f'☑️ Testing valid plain nanopub: {entry.name}')
        np_g = Dataset()
        np_g.parse(entry.path)
        np = Nanopub(conf=testsuite_conf, rdf=np_g)
        assert np.is_valid


def test_testsuite_valid_signed(testsuite: NanopubTestSuite):
    for entry in testsuite.get_valid(TestSuiteSubfolder.SIGNED):
        print(f'☑️ Testing valid signed nanopub: {entry.name}')
        np = Nanopub(conf=testsuite_conf, rdf=entry.path)
        assert np.is_valid
        assert np.metadata.trusty is not None
        assert np.metadata.signature is not None
        assert java_wrap.check_trusty_with_signature(np)


def test_testsuite_valid_trusty(testsuite: NanopubTestSuite):
    for entry in testsuite.get_valid(TestSuiteSubfolder.TRUSTY):
        print(f'☑️ Testing valid trusty nanopub: {entry.name}')
        np = Nanopub(conf=testsuite_conf, rdf=entry.path)
        assert np.is_valid
        assert np.metadata.trusty is not None


def test_testsuite_sign_valid(testsuite: NanopubTestSuite):
    """Sign plain nanopubs and compare the trusty URI to the one generated by nanopub-java."""
    for case in testsuite.get_transform_cases("rsa-key1"):
        print(f'✒️ Testing signing: {case.plain.name}')
        np_g = Dataset()
        np_g.parse(case.plain.path)
        np = Nanopub(conf=testsuite_conf, rdf=np_g)
        java_np = java_wrap.sign(np)
        np.sign()
        assert np.has_valid_signature
        assert np.has_valid_trusty
        assert np.is_valid
        assert java_wrap.check_trusty_with_signature(np)
        assert np.source_uri == java_np


def test_testsuite_valid_signature(testsuite: NanopubTestSuite):
    for entry in testsuite.get_valid(TestSuiteSubfolder.SIGNED):
        print(f'✅ Testing validating signed nanopub: {entry.name}')
        np = Nanopub(conf=testsuite_conf, rdf=entry.path)
        assert np.is_valid
        if np.metadata.algorithm and str(np.metadata.algorithm).upper() != "RSA":
            print(f'  Skipping signature check: algorithm {np.metadata.algorithm} not supported')
            continue
        assert np.has_valid_signature
        assert np.has_valid_trusty
        assert java_wrap.check_trusty_with_signature(np)


def test_testsuite_invalid_plain(testsuite: NanopubTestSuite):
    for entry in testsuite.get_invalid(TestSuiteSubfolder.PLAIN):
        print(f'❎ Testing invalid nanopub: {entry.name}')
        with pytest.raises(MalformedNanopubError):
            np = Nanopub(conf=testsuite_conf, rdf=entry.path)
            np.is_valid
