from pathlib import Path

import pytest
from nanopub_testsuite_connector import TestSuiteSubfolder
from rdflib import Dataset

from nanopub import Nanopub
from nanopub.utils import MalformedNanopubError
from tests.conftest import java_wrap, testsuite_conf, _suite


@pytest.mark.parametrize(
    "entry",
    _suite.get_valid(TestSuiteSubfolder.PLAIN),
    ids=lambda e: e.name,
)
def test_testsuite_valid_plain(entry):
    print(f"☑️ Testing valid plain nanopub: {entry.path}")

    np_g = Dataset()
    np_g.parse(entry.path)

    np = Nanopub(
        conf=testsuite_conf,
        rdf=np_g
    )
    assert np.is_valid


@pytest.mark.parametrize(
    "entry",
    _suite.get_valid(TestSuiteSubfolder.SIGNED),
    ids=lambda e: e.name,
)
def test_testsuite_valid_signed(entry):
    print(f"☑️ Testing valid signed nanopub: {entry.path}")

    np = Nanopub(conf=testsuite_conf, rdf=entry.path)
    assert np.is_valid
    assert np.metadata.trusty is not None
    assert np.metadata.signature is not None
    assert java_wrap.check_trusty_with_signature(np)
    # TODO: we should be able to validate this signature?
    # assert np.has_valid_signature


@pytest.mark.parametrize(
    "entry",
    _suite.get_valid(TestSuiteSubfolder.TRUSTY),
    ids=lambda e: e.name,
)
def test_testsuite_valid_trusty(entry):
    print(f"☑️ Testing valid trusty nanopub: {entry.path}")

    np = Nanopub(conf=testsuite_conf, rdf=entry.path)
    assert np.is_valid
    assert np.metadata.trusty is not None


@pytest.mark.parametrize(
    "tc",
    _suite.get_transform_cases("rsa-key1"),
    ids=lambda tc: f"{tc.key_name}/{tc.plain.name}",
)
def test_testsuite_sign_valid(tc):
    """Test to sign various files from transform and valid folder.
    Compare the generated trusty URI to the one generated by nanopub-java"""
    print(f"✒️ Testing signing: {tc.plain.path}")

    np_g = Dataset()
    np_g.parse(tc.plain.path)

    np = Nanopub(
        conf=testsuite_conf,
        rdf=np_g
    )
    java_np = java_wrap.sign(np)
    np.sign()
    assert np.has_valid_signature
    assert np.has_valid_trusty
    assert np.is_valid
    assert java_wrap.check_trusty_with_signature(np)
    assert np.source_uri == java_np


@pytest.mark.parametrize(
    "tc",
    _suite.get_transform_cases("rsa-key1"),
    ids=lambda tc: f"{tc.key_name}/{tc.plain.name}",
)
def test_testsuite_valid_signature(tc):
    print(f"✅ Testing validating signed nanopub: {tc.signed.path}")
    np = Nanopub(
        conf=testsuite_conf,
        rdf=Path(tc.signed.path)
    )
    assert np.is_valid
    assert np.has_valid_signature
    assert np.has_valid_trusty
    assert java_wrap.check_trusty_with_signature(np)


@pytest.mark.parametrize(
    "entry",
    _suite.get_invalid(TestSuiteSubfolder.PLAIN),
    ids=lambda e: e.name,
)
def test_testsuite_invalid_plain(entry):
    print(f"❎ Testing invalid nanopub: {entry.path}")

    try:
        np = Nanopub(
            conf=testsuite_conf,
            rdf=Path(entry.path)
        )
        np.is_valid
        assert False
    except MalformedNanopubError as e:
        print(e)
        assert True
