name: Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12.4" ]
        rdflib-version:
          - rdflib==6.0.2
          - rdflib==7.1.4
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies with ${{ matrix.rdflib-version }}
        run: |
          poetry install --only test,dev
          poetry add ${{ matrix.rdflib-version }}

      - name: Setup nanopub profile (including RSA keys)
        run: |
          poetry run np setup --orcid-id https://orcid.org/0000-0000-0000-0000 --no-publish --name test --newkeys

      - name: Test with pytest
        run: |
          poetry run pytest -v --cov

      - name: Publish coverage to Coveralls
        run: |
          poetry run coverage xml
          poetry run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }} - ${{ matrix.rdflib-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Install coveralls
        run: pip3 install --upgrade coveralls
      - name: Finished
        run: coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
