# This workflow will install Python dependencies, run tests and lint with a single version of Python on different os's
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Test with pytest - No RSA key tests
        run: |
           pytest --no_rsa_key -m 'no_rsa_key'
      - name: Setup nanopub profile (including RSA keys) for linux
        if: runner.os == 'Linux'
        run: |
              printf '\n' | setup_profile --orcid_id 'https://orcid.org/1234-1234-1234-1234' --no-publish --name 'test'
      - name: Setup nanopub profile (including RSA keys) for Windows
        if: runner.os == 'Windows'
        run: |
              printf '\n' > setup_profile --orcid_id 'https://orcid.org/1234-1234-1234-1234' --no-publish --name 'test'
      - name: Test with pytest
        run: |
          pytest --cov
      - name: Publish coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ env.COVERALLS_REPO_TOKEN }}
        run: |
          coverage xml
          coveralls
      - name: Build Sphinx docs
        run: |
          cd docs
          make html
