# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and update docs

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install ".[test,dev]"

      - name: Lint with flake8, isort and mypy
        run: bash scripts/lint.sh

      - name: Setup nanopub profile (including RSA keys)
        run: |
           np setup --orcid_id https://orcid.org/1234-1234-1234-1234 --no-publish --name test --newkeys

      - name: Test with pytest
        run: |
          pytest --cov

      - name: Publish coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ env.COVERALLS_REPO_TOKEN }}
        run: |
          coverage xml
          coveralls


  build-docs:
    needs: [ tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ".[doc]"

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Deploy docs with mkdocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
